version: '3.8'

services:
  bot:
    build: .
    container_name: bot_service
    environment:
      - BOT_TOKEN=7689649103:AAEkOak9caU-obULdGqU0DTmkQZhNuZIRis
      - URL=https://fastapi-service.onrender.com
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python3 bot.py

  api:
    build: .
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 10000